[project]
name = "digital-library"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.0",
    "sqlalchemy==2.0.36",
    "uvicorn>=0.38.0",
]
